version: "3"

services:
  django:
    image: 221.155.148.197:5000/cafe_server-django:latest
    container_name: cafe-moa
    networks:
      - internal_network
    environment:
      - RUNNING_ENV=local
      - TZ=Asia/Seoul
    ports:
      - "172.22.0.1:8001:80"

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
