version: "3"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cafe-moa
    networks:
      - internal_network
    environment:
      - RUNNING_ENV=local
      - TZ=Asia/Seoul
    volumes:
      - ./:/webapp/server/
    ports:
      - "8001:80"

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
