version: "3"

services:
  django:
    image: ${REGISTRY}/cafe_server-django:latest
    container_name: cafe-moa
    networks:
      - internal_network
    environment:
      - RUNNING_ENV=development
      - TZ=Asia/Seoul
    volumes:
      - ${ENV_PATH}/secrets.json:/webapp/server/cafe_backend/settings/secrets.json
      - ./logs:/webapp/server/logs:rw
    ports:
      - "0.0.0.0:8001:80"

  redis-master:
    image: redis:latest
    container_name: redis-master
    networks:
      - internal_network

  redis-slave:
    image: redis:latest
    container_name: redis-slave
    networks:
      - internal_network
    command: redis-server --slaveof redis-master 6379

networks:
  internal_network:
    driver: bridge

