version: "3"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-tour-backend
    environment:
      - RUNNING_ENV=base
      - TZ=Asia/Seoul
    volumes:
      - ./:/webapp/server/
    ports:
      - "8080:8000"

