# Generated by Django 4.1.7 on 2023-05-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_add_cafe_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
