# Generated by Django 4.1.7 on 2023-05-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_cafe_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='cafe',
            name='categories',
            field=models.ManyToManyField(to='cafe.cafecategory'),
        ),
    ]
