# Generated by Django 4.1.7 on 2024-01-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='cafe_id',
            new_name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='menuimage',
            old_name='cafe_id',
            new_name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='cafe_id',
            new_name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='cafe_id',
            new_name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='thumbnail',
            old_name='cafe_id',
            new_name='restaurant_id',
        ),
    ]
